require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'CrudDemoApp' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app'

  pod 'RNFBFirestore', :path => '../node_modules/@react-native-firebase/firestore'

  pod 'RNFBAuth', :path => '../node_modules/@react-native-firebase/auth'

  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

  pod 'RNGoogleSignin', :path => '../node_modules/@react-native-community/google-signin'

  pod 'react-native-twitter-signin', :path => '../node_modules/react-native-twitter-signin'

  target 'CrudDemoAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'CrudDemoApp-tvOS' do
  # Pods for CrudDemoApp-tvOS

  target 'CrudDemoApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
